image: ghcr.io/astral-sh/uv:python3.13-alpine

variables:
  UV_CACHE_DIR: .uv-cache
  GIT_CLEAN_FLAGS: -ffdx -e $UV_CACHE_DIR

cache:
  - key:
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR

test:
  script:
    - uv sync
    - uv run pytest tests/
    - uv cache prune --ci
