image: ghcr.io/astral-sh/uv:python3.13-alpine

variables:
  UV_CACHE_DIR: .uv-cache
  GIT_CLEAN_FLAGS: -ffdx -e $UV_CACHE_DIR

cache:
  - key:
      files:
        - uv.lock
    paths:
      - $UV_CACHE_DIR

test:
  script:
    - apk add git build-base make
    - uv sync --group build --no-group compile
    - DD_FETCH=1 DD_CUDD=1 DD_CUDD_ADD=1 uv sync --all-groups
    - uv run pytest
    - uv cache prune --ci
